In [1]:
import torch
import numpy as np


In [5]:
my_list = [[1,2,3,4,5],
          [6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [6]:
np1 = np.random.rand(3,4)
np1

array([[0.22069233, 0.64258131, 0.73832457, 0.75925628],
       [0.9504415 , 0.71103054, 0.66062455, 0.85767616],
       [0.73048292, 0.39460808, 0.92664575, 0.69354101]])

In [7]:
np1.dtype

dtype('float64')

In [13]:
tensor_2d = torch.rand(3,4)
tensor_2d
#tensor_2d.dtype

tensor([[0.0892, 0.1827, 0.4277, 0.6735],
        [0.1655, 0.3981, 0.3958, 0.2301],
        [0.9462, 0.2608, 0.1583, 0.5718]])

In [10]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
##Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.2207, 0.6426, 0.7383, 0.7593],
        [0.9504, 0.7110, 0.6606, 0.8577],
        [0.7305, 0.3946, 0.9266, 0.6935]], dtype=torch.float64)